# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CocoTextImage',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=256)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('set', models.CharField(choices=[('TRN', 'Training'), ('VAL', 'Validation'), ('TST', 'Test')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CocoTextInstance',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('polygon', django.contrib.postgres.fields.jsonb.JSONField()),
                ('text', models.CharField(max_length=10485760)),
                ('legibility', models.CharField(choices=[('L', 'Legible'), ('I', 'Illegible')], max_length=1)),
                ('language', models.CharField(max_length=128)),
                ('from_v1', models.BooleanField(default=False)),
                ('polygon_verified', models.BooleanField(default=False)),
                ('text_verified', models.BooleanField(default=False)),
                ('legibility_verified', models.BooleanField(default=False)),
                ('language_verified', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CocoTextImage')),
            ],
        ),
        migrations.CreateModel(
            name='CocoTextInstanceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CocoTextImage')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(default='0.0.1', max_length=16)),
                ('max_assignments', models.PositiveSmallIntegerField(default=1)),
                ('auto_approval_delay_in_seconds', models.PositiveIntegerField(default=1209600)),
                ('lifetime_in_seconds', models.PositiveIntegerField(default=2592000)),
                ('assignment_duration_in_seconds', models.PositiveIntegerField(default=3600)),
                ('reward', models.DecimalField(decimal_places=4, max_digits=8)),
                ('title', models.CharField(max_length=256)),
                ('keywords', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=4096)),
                ('question', models.CharField(max_length=10485760)),
            ],
        ),
        migrations.CreateModel(
            name='MturkAssignment',
            fields=[
                ('assignment_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('assignment_status', models.CharField(choices=[('S', 'Submitted'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1)),
                ('auto_approval_time', models.DateTimeField()),
                ('accept_time', models.DateTimeField()),
                ('submit_time', models.DateTimeField()),
                ('approval_time', models.DateTimeField()),
                ('rejection_time', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MturkHit',
            fields=[
                ('hit_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('hit_type_id', models.CharField(max_length=128)),
                ('hit_group_id', models.CharField(max_length=128)),
                ('creation_time', models.DateTimeField()),
                ('expiration', models.DateTimeField()),
                ('hit_status', models.CharField(choices=[('A', 'Assignable'), ('U', 'Unassignable'), ('R', 'Reviewable'), ('E', 'Reviewing'), ('D', 'Disposed')], max_length=1)),
                ('hit_review_status', models.CharField(choices=[('N', 'NotReviewed'), ('M', 'MarkedForReview'), ('A', 'ReviewedAppropriate'), ('I', 'ReviewedInappropriate')], max_length=1)),
                ('num_assignments_pending', models.PositiveSmallIntegerField()),
                ('num_assignments_available', models.PositiveSmallIntegerField()),
                ('num_assignments_completed', models.PositiveSmallIntegerField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='api.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='MturkWorker',
            fields=[
                ('worker_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PolygonVerificationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon_verification_tasks', to='api.Experiment')),
                ('mturk_hit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polygon_verification_task', to='api.MturkHit')),
            ],
        ),
        migrations.CreateModel(
            name='TextInstanceForPolygonVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('CO', 'Correct'), ('WR', 'WRONG'), ('US', 'Unsure'), ('UV', 'Unverified')], default='UV', max_length=1)),
                ('assignments', models.ManyToManyField(related_name='text_instances_for_polygon_verification', to='api.MturkAssignment')),
                ('text_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_instance_for_polygon_verification', to='api.CocoTextInstance')),
            ],
        ),
        migrations.AddField(
            model_name='polygonverificationtask',
            name='text_instances',
            field=models.ManyToManyField(to='api.TextInstanceForPolygonVerification'),
        ),
        migrations.AddField(
            model_name='mturkassignment',
            name='hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.MturkHit'),
        ),
        migrations.AddField(
            model_name='mturkassignment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.MturkWorker'),
        ),
    ]
