# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocotextinstance',
            name='text_class',
            field=models.CharField(choices=[('M', 'MachinePrinted'), ('H', 'Handwritten'), ('O', 'Others')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cocotextinstance',
            name='language',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cocotextinstance',
            name='text',
            field=models.CharField(max_length=10485760, null=True),
        ),
    ]
