# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170606_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygonverificationtask',
            name='text_instances',
        ),
        migrations.RemoveField(
            model_name='textinstanceforpolygonverification',
            name='assignments',
        ),
        migrations.AddField(
            model_name='textinstanceforpolygonverification',
            name='verification_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_instances', to='api.PolygonVerificationTask'),
        ),
        migrations.AlterField(
            model_name='textinstanceforpolygonverification',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
