# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170606_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='reward',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
