# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 23:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170606_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='assignment_duration_in_seconds',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='auto_approval_delay_in_seconds',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='lifetime_in_seconds',
        ),
        migrations.AddField(
            model_name='experiment',
            name='assignment_duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
        migrations.AddField(
            model_name='experiment',
            name='auto_approval_delay',
            field=models.DurationField(default=datetime.timedelta(14)),
        ),
        migrations.AddField(
            model_name='experiment',
            name='lifetime',
            field=models.DurationField(default=datetime.timedelta(30)),
        ),
    ]
