# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170606_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinstanceforpolygonverification',
            name='verification_status',
            field=models.CharField(choices=[('CO', 'Correct'), ('WR', 'WRONG'), ('US', 'Unsure'), ('UV', 'Unverified')], default='UV', max_length=2),
        ),
    ]
