# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170606_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='experiment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
