# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170607_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='question',
            field=models.TextField(),
        ),
    ]
