# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170607_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinstanceforpolygonverification',
            name='text_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_polygon_verification', to='api.CocoTextInstance'),
        ),
    ]
