# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170607_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinstanceforpolygonverification',
            name='verification_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_instances', to='api.PolygonVerificationTask'),
        ),
    ]
