# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170608_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mturkhit',
            old_name='hit_id',
            new_name='id',
        ),
    ]
