# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 19:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170608_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mturkassignment',
            name='accept_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mturkassignment',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mturkassignment',
            name='approval_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mturkassignment',
            name='auto_approval_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mturkassignment',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mturkassignment',
            name='rejection_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mturkassignment',
            name='submit_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mturkassignment',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.MturkWorker'),
        ),
    ]
