# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170608_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_workers', to='api.Experiment')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_workers', to='api.MturkWorker')),
            ],
        ),
        migrations.RenameField(
            model_name='polygonverificationtask',
            old_name='mturk_hit',
            new_name='hit',
        ),
        migrations.AddField(
            model_name='textinstanceforpolygonverification',
            name='gt_verification_status',
            field=models.CharField(choices=[('CO', 'Correct'), ('WR', 'WRONG'), ('US', 'Unsure'), ('UV', 'Unverified')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='textinstanceforpolygonverification',
            name='sentinel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='experimentworker',
            unique_together=set([('experiment', 'worker')]),
        ),
    ]
