# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyannot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='admin_mark',
            field=models.CharField(choices=[('U', 'Unchecked'), ('C', 'Correct'), ('W', 'Wrong'), ('R', 'RevisionOrFurtherWork')], default='U', max_length=1),
        ),
    ]
