# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyannot', '0002_submission_admin_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='hasRemainingText',
            field=models.BooleanField(default=True),
        ),
    ]
