# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyannot', '0003_auto_20170706_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='hints',
        ),
    ]
