# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyannot', '0003_response_hasremainingtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='hasRemainingText',
        ),
    ]
