# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyannot', '0004_remove_task_hints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='worker',
            new_name='project_worker',
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('task', 'submission', 'project_worker')]),
        ),
    ]
