# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyannot', '0004_remove_response_hasremainingtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='misc_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
