# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 23:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyannot', '0005_auto_20170710_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
