# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyannot', '0008_auto_20170710_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='submission_idx',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('submission', 'submission_idx')]),
        ),
    ]
