# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 01:52
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CocoTextImage',
            fields=[
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=256)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('set', models.CharField(choices=[('TRN', 'Training'), ('VAL', 'Validation'), ('TST', 'Test')], max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CocoTextInstance',
            fields=[
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('polygon', django.contrib.postgres.fields.jsonb.JSONField()),
                ('text', models.CharField(max_length=256, null=True)),
                ('legibility', models.CharField(choices=[('L', 'Legible'), ('I', 'Illegible')], max_length=1)),
                ('text_class', models.CharField(choices=[('M', 'MachinePrinted'), ('H', 'Handwritten'), ('O', 'Others')], max_length=1, null=True)),
                ('language', models.CharField(max_length=128, null=True)),
                ('from_v1', models.BooleanField(default=False)),
                ('polygon_verification', models.CharField(choices=[('U', 'Unverified'), ('C', 'Correct'), ('W', 'Wrong')], default='U', max_length=1)),
                ('text_verification', models.CharField(choices=[('U', 'Unverified'), ('C', 'Correct'), ('W', 'Wrong')], default='U', max_length=1)),
                ('legibility_verification', models.CharField(choices=[('U', 'Unverified'), ('C', 'Correct'), ('W', 'Wrong')], default='U', max_length=1)),
                ('language_verification', models.CharField(choices=[('U', 'Unverified'), ('C', 'Correct'), ('W', 'Wrong')], default='U', max_length=1)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.CocoTextImage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(default='0.0.1', max_length=16)),
                ('max_assignments', models.PositiveSmallIntegerField(default=1)),
                ('auto_approval_delay', models.DurationField(default=datetime.timedelta(14))),
                ('lifetime', models.DurationField(default=datetime.timedelta(30))),
                ('assignment_duration', models.DurationField(default=datetime.timedelta(0, 3600))),
                ('reward', models.DecimalField(decimal_places=2, max_digits=4)),
                ('title', models.CharField(max_length=256)),
                ('keywords', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('question', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MturkAssignment',
            fields=[
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('assignment_status', models.CharField(choices=[('S', 'Submitted'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1)),
                ('auto_approval_time', models.DateTimeField(null=True)),
                ('accept_time', models.DateTimeField(null=True)),
                ('submit_time', models.DateTimeField(null=True)),
                ('approval_time', models.DateTimeField(null=True)),
                ('rejection_time', models.DateTimeField(null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('answer_xml', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MturkHit',
            fields=[
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('hit_type_id', models.CharField(max_length=128)),
                ('hit_group_id', models.CharField(max_length=128)),
                ('creation_time', models.DateTimeField()),
                ('expiration', models.DateTimeField()),
                ('hit_status', models.CharField(choices=[('A', 'Assignable'), ('U', 'Unassignable'), ('R', 'Reviewable'), ('E', 'Reviewing'), ('D', 'Disposed')], max_length=1)),
                ('hit_review_status', models.CharField(choices=[('N', 'NotReviewed'), ('M', 'MarkedForReview'), ('A', 'ReviewedAppropriate'), ('I', 'ReviewedInappropriate')], max_length=1)),
                ('num_assignments_pending', models.PositiveSmallIntegerField()),
                ('num_assignments_available', models.PositiveSmallIntegerField()),
                ('num_assignments_completed', models.PositiveSmallIntegerField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='common.Experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MturkWorker',
            fields=[
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mturkassignment',
            name='hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='common.MturkHit'),
        ),
        migrations.AddField(
            model_name='mturkassignment',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='common.MturkWorker'),
        ),
    ]
