# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocotextinstance',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='common.CocoTextImage'),
        ),
    ]
