# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170613_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationType',
            fields=[
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
                ('keywords', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('qualification_type_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('test', models.TextField()),
                ('test_duration', models.DurationField()),
                ('answer_key', models.TextField(null=True)),
                ('retry_delay', models.DurationField()),
                ('is_requestable', models.BooleanField()),
                ('auto_granted', models.BooleanField()),
                ('auto_granted_value', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
