# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_qualificationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationRequest',
            fields=[
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('test', models.TextField()),
                ('answer', models.TextField()),
                ('submit_time', models.DateTimeField()),
                ('qualification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.QualificationType')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.MturkWorker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
