# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170704_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocotextinstance',
            name='parent_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CocoTextInstance'),
        ),
        migrations.AddField(
            model_name='mturkhittype',
            name='slug',
            field=models.CharField(default='TODO_REMOVE_THIS', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='cocotextinstance',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_instances', to='common.CocoTextImage'),
        ),
        migrations.AlterField(
            model_name='cocotextinstance',
            name='legibility',
            field=models.CharField(choices=[('L', 'Legible'), ('I', 'Illegible')], max_length=1, null=True),
        ),
    ]
