# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20170706_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mturkhittype',
            name='slug',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
