# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_cocotextinstance_stage_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='qualificationrequest',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
