# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_qualificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mturkworker',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
