# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20170706_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationtype',
            name='slug',
            field=models.CharField(default='annot-verification-test', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
