# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_qualificationtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationtype',
            name='auto_granted_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
