# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20170710_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocotextinstance',
            name='parent_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_instances', to='common.CocoTextInstance'),
        ),
        migrations.AlterField(
            model_name='mturkassignment',
            name='hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='common.MturkHit'),
        ),
        migrations.AlterField(
            model_name='mturkassignment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='common.MturkWorker'),
        ),
        migrations.AlterField(
            model_name='mturkhit',
            name='hit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='common.MturkHitType'),
        ),
        migrations.AlterField(
            model_name='qualificationrequest',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='common.MturkWorker'),
        ),
    ]
