# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textannot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('U', 'Unassigned'), ('F', 'Finished'), ('P', 'Pending'), ('D', 'Dispute')], default='U', max_length=1),
        ),
    ]
