# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textannot', '0002_content_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworker',
            name='mturk_worker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textannot_worker', to='common.MturkWorker'),
        ),
    ]
