# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textannot', '0003_auto_20180423_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworker',
            name='nickname',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
