# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textannot', '0004_projectworker_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='textannot.Submission'),
        ),
    ]
