# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textannot', '0005_auto_20180423_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='illegible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='unknownLanguage',
            field=models.BooleanField(default=False),
        ),
    ]
