# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textannot', '0006_auto_20180503_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='textannot.Submission'),
        ),
    ]
