# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 02:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consensus_num', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('U', 'Unassigned'), ('P', 'Pending'), ('C', 'Completed')], default='U', max_length=1)),
                ('sentinel', models.BooleanField(default=False)),
                ('consensus', models.CharField(choices=[('D', 'Dispute'), ('C', 'Correct'), ('W', 'Wrong')], max_length=1, null=True)),
                ('gt_verification', models.CharField(choices=[('U', 'Unverified'), ('C', 'Correct'), ('W', 'Wrong')], max_length=1, null=True)),
                ('num_responses', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mturk_worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polyverif_worker', to='common.MturkWorker')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workers', to='polyverif.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('verification', models.CharField(choices=[('U', 'Unverified'), ('C', 'Correct'), ('W', 'Wrong')], max_length=1)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polyverif.Content')),
                ('project_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polyverif.ProjectWorker')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField()),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polyverif_submission', to='common.MturkAssignment')),
                ('project_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='polyverif.ProjectWorker')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('hit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polyverif_task', to='common.MturkHit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='polyverif.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='polyverif.Task'),
        ),
        migrations.AddField(
            model_name='response',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polyverif.Submission'),
        ),
        migrations.AddField(
            model_name='content',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='polyverif.Project'),
        ),
        migrations.AddField(
            model_name='content',
            name='tasks',
            field=models.ManyToManyField(related_name='contents', to='polyverif.Task'),
        ),
        migrations.AddField(
            model_name='content',
            name='text_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polyverif_content', to='common.CocoTextInstance'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('task', 'project_worker')]),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('submission', 'content', 'project_worker')]),
        ),
    ]
