# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 01:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonVerificationInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sentinel', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolygonVerificationSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField()),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='common.MturkAssignment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolygonVerificationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polyverif_tasks', to='common.Experiment')),
                ('hit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.MturkHit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='polygonverificationinstance',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_instances', to='polyverif.PolygonVerificationTask'),
        ),
        migrations.AddField(
            model_name='polygonverificationinstance',
            name='text_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_polygon_verification', to='common.CocoTextInstance'),
        ),
    ]
