# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyverif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygonverificationtask',
            name='hit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polyverif_task', to='common.MturkHit'),
        ),
    ]
