# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyverif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='consensus_num',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
