# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyverif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='polyverif.Project'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polyverif_content', to='common.CocoTextInstance'),
        ),
        migrations.AlterField(
            model_name='projectworker',
            name='mturk_worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polyverif_worker', to='common.MturkWorker'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polyverif_submission', to='common.MturkAssignment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polyverif_task', to='common.MturkHit'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='polyverif.Project'),
        ),
    ]
