# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 20:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170613_2029'),
        ('polyverif', '0002_auto_20170611_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('U', 'Unassigned'), ('P', 'Pending'), ('C', 'Completed')], max_length=1)),
                ('num_responses_required', models.PositiveSmallIntegerField()),
                ('sentinel', models.BooleanField(default=False)),
                ('gt_verification', models.CharField(choices=[('U', 'Unverified'), ('C', 'Correct'), ('W', 'Wrong')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('hit_settings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.HitSettings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('verification', models.CharField(choices=[('U', 'Unverified'), ('C', 'Correct'), ('W', 'Wrong')], max_length=1)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polyverif.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='common.MturkAssignment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('num_submissions_required', models.PositiveSmallIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('hit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='common.MturkHit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='polyverif.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('blocked', models.BooleanField(default=False)),
                ('mturk_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workers', to='common.MturkWorker')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workers', to='polyverif.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='polygonverificationinstance',
            name='task',
        ),
        migrations.RemoveField(
            model_name='polygonverificationinstance',
            name='text_instance',
        ),
        migrations.RemoveField(
            model_name='polygonverificationsubmission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='polygonverificationtask',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='polygonverificationtask',
            name='hit',
        ),
        migrations.DeleteModel(
            name='PolygonVerificationInstance',
        ),
        migrations.DeleteModel(
            name='PolygonVerificationSubmission',
        ),
        migrations.DeleteModel(
            name='PolygonVerificationTask',
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='polyverif.Task'),
        ),
        migrations.AddField(
            model_name='submission',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='polyverif.Worker'),
        ),
        migrations.AddField(
            model_name='response',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polyverif.Submission'),
        ),
        migrations.AddField(
            model_name='response',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polyverif.Worker'),
        ),
        migrations.AddField(
            model_name='content',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='polyverif.Project'),
        ),
        migrations.AddField(
            model_name='content',
            name='tasks',
            field=models.ManyToManyField(related_name='contents', to='polyverif.Task'),
        ),
        migrations.AddField(
            model_name='content',
            name='text_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.CocoTextInstance'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('submission', 'content', 'worker')]),
        ),
    ]
