# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyverif', '0002_auto_20170703_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='num_responses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
