# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyverif', '0003_content_num_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworker',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workers', to='polyverif.Project'),
        ),
        migrations.AlterField(
            model_name='response',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polyverif.Content'),
        ),
        migrations.AlterField(
            model_name='response',
            name='project_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polyverif.ProjectWorker'),
        ),
        migrations.AlterField(
            model_name='response',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polyverif.Submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='project_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='polyverif.ProjectWorker'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='polyverif.Task'),
        ),
    ]
