# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyverif', '0003_auto_20170613_2029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([]),
        ),
    ]
