# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyverif', '0004_auto_20170614_1830'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('submission', 'content', 'worker')]),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('task', 'worker')]),
        ),
    ]
