# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyverif', '0004_auto_20170703_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='num_responses_required',
        ),
    ]
