# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyverif', '0005_remove_content_num_responses_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('U', 'Unassigned'), ('P', 'Pending'), ('C', 'Completed')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
