# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyverif', '0005_auto_20170619_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='consensus',
            field=models.CharField(choices=[('U', 'Unverified'), ('C', 'Correct'), ('W', 'Wrong')], max_length=1, null=True),
        ),
    ]
