# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170613_2029'),
        ('polyverif', '0006_content_consensus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together=set([('project', 'mturk_worker')]),
        ),
    ]
