# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyverif', '0007_auto_20170704_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tasks',
            field=models.ManyToManyField(related_name='contents', to='polyverif.Task'),
        ),
    ]
